# Generated by Django 5.2.4 on 2025-07-11 01:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('stars_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('num_rooms', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('num_beds', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('is_available', models.BooleanField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.roomtype')),
            ],
        ),
    ]
