# Generated by Django 5.2.4 on 2025-07-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_hotel_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='is_vip',
        ),
    ]
